### ISSUE TITLE
Question about load model

### ISSUE THREAD

**Issue by 97z** [Double680/CrossAug#2]
If I first run this code, there will have an error:
Traceback (most recent call last):
  File "/root/CrossAug/main.py", line 159, in <module>
    args = init()
  File "/root/CrossAug/main.py", line 50, in init
    load_models(args, config[args.approach])
  File "/root/CrossAug/main.py", line 76, in load_models
    args.model = torch.compile(getattr(sys.modules[__name__], args.approach)(args).to(args.device))
  File "/root/CrossAug/models/CrossAug.py", line 53, in __init__
    self.adj = args.overall_mat
AttributeError: 'Namespace' object has no attribute 'overall_mat'
That's because when get_inter_mat(args), the code will not generate the overall_mat unless I have overall_mat.npy before. So I comment the code in CrossAug.py:
        #self.adj = args.overall_mat
        self.d1_norm_adj, self.d1_user_degree = self.get_norm_adj(self.d1_adj)
        self.d2_norm_adj, self.d2_user_degree = self.get_norm_adj(self.d2_adj)
        #self.norm_adj, self.user_degree = self.get_norm_adj(self.adj)
and it works. 
If this event will affect the results? Thank you for any reply!

**Comment by 97z** [comment]
It's a great work! I can get the same results in paper.

**Comment by YudiXiong** [comment]
> If I first run this code, there will have an error: Traceback (most recent call last): File "/root/CrossAug/main.py", line 159, in args = init() File "/root/CrossAug/main.py", line 50, in init load_models(args, config[args.approach]) File "/root/CrossAug/main.py", line 76, in load_models args.model = torch.compile(getattr(sys.modules[**name**], args.approach)(args).to(args.device)) File "/root/CrossAug/models/CrossAug.py", line 53, in **init** self.adj = args.overall_mat AttributeError: 'Namespace' object has no attribute 'overall_mat' That's because when get_inter_mat(args), the code will not generate the overall_mat unless I have overall_mat.npy before. So I comment the code in CrossAug.py: #self.adj = args.overall_mat self.d1_norm_adj, self.d1_user_degree = self.get_norm_adj(self.d1_adj) self.d2_norm_adj, self.d2_user_degree = self.get_norm_adj(self.d2_adj) #self.norm_adj, self.user_degree = self.get_norm_adj(self.adj) and it works. If this event will affect the results? Thank you for any reply!

Could you please let me know what the format of the processed data looks like? I'm having trouble obtaining the data after processing, and I keep encountering errors during the processing stage after downloading the data.

**Comment by YudiXiong** [comment]
> Could you please let me know what the format of the processed data looks like? I'm having trouble obtaining the data after processing, and I keep encountering errors during the processing stage after downloading the data.

================ Data Filtering ================
Dataset: Amazon.  Domain: Music.
Initializing...
Initialized!
Filtering...
Load ratings: 4543369it [00:08, 563711.62it/s]
Statistics (Original):
  # Users: 1944316
  # Items: 434060
  # Inters: 4470089

Load metadata: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "filter.py", line 97, in <module>
    filter(args)
  File "filter.py", line 52, in filter
    meta_items = load_metadata(args)
  File "/CrossAug-main/datasets/utils.py", line 43, in load_metadata
    for line in tqdm(fp, desc='Load metadata'):
  File "/home/X/.conda/envs/Pytorch/lib/python3.7/site-packages/tqdm/std.py", line 1130, in __iter__
    for obj in iterable:
  File "/home/X/.conda/envs/Pytorch/lib/python3.7/gzip.py", line 385, in readline
    return self._buffer.readline(size)
  File "/home/X/.conda/envs/Pytorch/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/X/.conda/envs/Pytorch/lib/python3.7/gzip.py", line 474, in read
    if not self._read_gzip_header():
  File "/home/X/.conda/envs/Pytorch/lib/python3.7/gzip.py", line 422, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'{"')

**Comment by Double680** [comment]
How about trying use Python 3.9+ according to the README.md instead of 3.7?

 

发件人: ***@***.*** ***@***.***> 代表 YudiXiong
发送时间: 2025年2月8日 16:13
收件人: Double680/CrossAug ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [Double680/CrossAug] Question about load model (Issue #2)

 

Could you please let me know what the format of the processed data looks like? I'm having trouble obtaining the data after processing, and I keep encountering errors during the processing stage after downloading the data.

================ Data Filtering ================
Dataset: Amazon. Domain: Music.
Initializing...
Initialized!
Filtering...
Load ratings: 4543369it [00:08, 563711.62it/s]
Statistics (Original):


Users: 1944316


Items: 434060


Inters: 4470089


Load metadata: 0it [00:00, ?it/s]
Traceback (most recent call last):
File "filter.py", line 97, in 
filter(args)
File "filter.py", line 52, in filter
meta_items = load_metadata(args)
File "/CrossAug-main/datasets/utils.py", line 43, in load_metadata
for line in tqdm(fp, desc='Load metadata'):
File "/home/X/.conda/envs/Pytorch/lib/python3.7/site-packages/tqdm/std.py", line 1130, in iter
for obj in iterable:
File "/home/X/.conda/envs/Pytorch/lib/python3.7/gzip.py", line 385, in readline
return self._buffer.readline(size)
File "/home/X/.conda/envs/Pytorch/lib/python3.7/_compression.py", line 68, in readinto
data = self.read(len(byte_view))
File "/home/X/.conda/envs/Pytorch/lib/python3.7/gzip.py", line 474, in read
if not self._read_gzip_header():
File "/home/X/.conda/envs/Pytorch/lib/python3.7/gzip.py", line 422, in _read_gzip_header
raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'{"')
